"""columns created

Revision ID: 36c1b7a20287
Revises: 
Create Date: 2024-05-01 04:03:20.486191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c1b7a20287'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dodopizza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('payment_sum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dodopizza_id'), 'dodopizza', ['id'], unique=False)
    op.create_table('khayriyai_ozod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('payment_sum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_khayriyai_ozod_id'), 'khayriyai_ozod', ['id'], unique=False)
    op.create_table('kitobz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('payment_sum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitobz_id'), 'kitobz', ['id'], unique=False)
    op.create_table('mavgi_somon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.Integer(), nullable=False),
    sa.Column('payment_sum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mavgi_somon_id'), 'mavgi_somon', ['id'], unique=False)
    op.create_table('mobile_networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('payment_sum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobile_networks_id'), 'mobile_networks', ['id'], unique=False)
    op.create_table('salomat_tj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('payment_sum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salomat_tj_id'), 'salomat_tj', ['id'], unique=False)
    op.create_table('shabakatj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.Integer(), nullable=False),
    sa.Column('payment_sum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shabakatj_id'), 'shabakatj', ['id'], unique=False)
    op.create_table('tojnet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.Integer(), nullable=False),
    sa.Column('payment_sum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tojnet_id'), 'tojnet', ['id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_tojnet_id'), table_name='tojnet')
    op.drop_table('tojnet')
    op.drop_index(op.f('ix_shabakatj_id'), table_name='shabakatj')
    op.drop_table('shabakatj')
    op.drop_index(op.f('ix_salomat_tj_id'), table_name='salomat_tj')
    op.drop_table('salomat_tj')
    op.drop_index(op.f('ix_mobile_networks_id'), table_name='mobile_networks')
    op.drop_table('mobile_networks')
    op.drop_index(op.f('ix_mavgi_somon_id'), table_name='mavgi_somon')
    op.drop_table('mavgi_somon')
    op.drop_index(op.f('ix_kitobz_id'), table_name='kitobz')
    op.drop_table('kitobz')
    op.drop_index(op.f('ix_khayriyai_ozod_id'), table_name='khayriyai_ozod')
    op.drop_table('khayriyai_ozod')
    op.drop_index(op.f('ix_dodopizza_id'), table_name='dodopizza')
    op.drop_table('dodopizza')
    # ### end Alembic commands ###
